# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='image_service',
  syntax='proto3',
  serialized_options=_b('Z\002pb'),
  serialized_pb=_b('\n\rservice.proto\x12\rimage_service\"\x1e\n\x0eToImageRequest\x12\x0c\n\x04text\x18\x01 \x01(\x0c\"6\n\x0fToImageResponse\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05\x32Z\n\x0eTransformation\x12H\n\x07ToImage\x12\x1d.image_service.ToImageRequest\x1a\x1e.image_service.ToImageResponseB\x04Z\x02pbb\x06proto3')
)




_TOIMAGEREQUEST = _descriptor.Descriptor(
  name='ToImageRequest',
  full_name='image_service.ToImageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='image_service.ToImageRequest.text', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=62,
)


_TOIMAGERESPONSE = _descriptor.Descriptor(
  name='ToImageResponse',
  full_name='image_service.ToImageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='image_service.ToImageResponse.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='image_service.ToImageResponse.x', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='image_service.ToImageResponse.y', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=118,
)

DESCRIPTOR.message_types_by_name['ToImageRequest'] = _TOIMAGEREQUEST
DESCRIPTOR.message_types_by_name['ToImageResponse'] = _TOIMAGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ToImageRequest = _reflection.GeneratedProtocolMessageType('ToImageRequest', (_message.Message,), dict(
  DESCRIPTOR = _TOIMAGEREQUEST,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:image_service.ToImageRequest)
  ))
_sym_db.RegisterMessage(ToImageRequest)

ToImageResponse = _reflection.GeneratedProtocolMessageType('ToImageResponse', (_message.Message,), dict(
  DESCRIPTOR = _TOIMAGERESPONSE,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:image_service.ToImageResponse)
  ))
_sym_db.RegisterMessage(ToImageResponse)


DESCRIPTOR._options = None

_TRANSFORMATION = _descriptor.ServiceDescriptor(
  name='Transformation',
  full_name='image_service.Transformation',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=120,
  serialized_end=210,
  methods=[
  _descriptor.MethodDescriptor(
    name='ToImage',
    full_name='image_service.Transformation.ToImage',
    index=0,
    containing_service=None,
    input_type=_TOIMAGEREQUEST,
    output_type=_TOIMAGERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRANSFORMATION)

DESCRIPTOR.services_by_name['Transformation'] = _TRANSFORMATION

# @@protoc_insertion_point(module_scope)
