# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import service_pb2 as service__pb2


class TransformationStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ToImage = channel.unary_unary(
        '/image_service.Transformation/ToImage',
        request_serializer=service__pb2.ToImageRequest.SerializeToString,
        response_deserializer=service__pb2.ToImageResponse.FromString,
        )


class TransformationServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ToImage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TransformationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ToImage': grpc.unary_unary_rpc_method_handler(
          servicer.ToImage,
          request_deserializer=service__pb2.ToImageRequest.FromString,
          response_serializer=service__pb2.ToImageResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'image_service.Transformation', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
